services:
  - type: worker
    name: discord-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: DISCORD_TOKEN
        sync: false