services:
  - type: worker
    name: discord-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: MTQyNzk3MDg5MzEzNjUzMTUxNw.G_FD-x.dB9N5lNjjCgRKqRUL77dpdNF10vTtbvyNdSl14
        sync: false